apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskgpt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskgpt
  template:
    metadata:
      labels:
        app: flaskgpt
    spec:
      containers:
        - name: flaskgpt
          image: roua863/devops:latest

          ports:
            - containerPort: 80
